version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm run coverage
      - store_artifacts:
          path: coverage
